// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	auth "gomall_demo/app/frontend/biz/router/auth"
	cart "gomall_demo/app/frontend/biz/router/cart"
	category "gomall_demo/app/frontend/biz/router/category"
	checkout "gomall_demo/app/frontend/biz/router/checkout"
	home "gomall_demo/app/frontend/biz/router/home"
	order "gomall_demo/app/frontend/biz/router/order"
	product "gomall_demo/app/frontend/biz/router/product"
	product_center "gomall_demo/app/frontend/biz/router/product_center"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	product_center.Register(r)

	auth.Register(r)

	checkout.Register(r)

	category.Register(r)

	cart.Register(r)

	order.Register(r)

	product.Register(r)

	home.Register(r)
}
