// Code generated by hertz generator.

package product_center

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductcenterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createproductcenterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateproductcenterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteproductcenterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchproductcentersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _product_centerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productcenterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productcenter0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
